### ISSUE TITLE
Running `vagrant up` hangs on NFS mounting (Vagrant 1.4.3)

### ISSUE THREAD

**Issue by tlhunter** [wunki/vagrant-freebsd#4] opened 2014-02-24 17:55 UTC
Vagrant hangs when booting this image while attempting to mount the NFS path. I'm not positive, but I believe Vagrant is failing at OS detection and executing `/etc/init.d/nfs-kernel-server` on the client. Running Linux Mint (Debian / Ubuntu) on the host.

```
$ vagrant -v
Vagrant 1.4.3
$ ls
Vagrantfile
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
[default] Clearing any previously set forwarded ports...
[default] Fixed port collision for 22 => 2222. Now on port 2200.
[default] Clearing any previously set network interfaces...
[default] Preparing network interfaces based on configuration...
[default] Forwarding ports...
[default] -- 22 => 2200 (adapter 1)
[default] Running 'pre-boot' VM customizations...
[default] Booting VM...
[default] Waiting for machine to boot. This may take a few minutes...
[default] Machine booted and ready!
[default] Configuring and enabling network interfaces...
[default] Exporting NFS shared folders...
Preparing to edit /etc/exports. Administrator privileges will be required...
sudo: /etc/init.d/nfs-kernel-server: command not found
[default] Mounting NFS shared folders...
```

I can, however, kill the boot process, then `vagrant ssh` to get in (the filesystem of course isn't mounted):

```
Preparing to edit /etc/exports. Administrator privileges will be required...
sudo: /etc/init.d/nfs-kernel-server: command not found
[default] Mounting NFS shared folders...
^C[default] Waiting for cleanup before exiting...
^C[default] Exiting immediately, without cleanup!
$ vagrant ssh
Last login: Mon Feb 24 17:41:56 2014 from 10.0.2.2
FreeBSD 10.0-RELEASE (GENERIC) #0 r260789: Thu Jan 16 22:34:59 UTC 2014

                                       _    _                  
                 __      ___   _ _ __ | | _(_)  ___  _ __ __ _ 
                 \ \ /\ / / | | | '_ \| |/ / | / _ \| '__/ _` |
                  \ V  V /| |_| | | | |   <| || (_) | | | (_| |
                   \_/\_/  \__,_|_| |_|_|\_\_(_)___/|_|  \__, |
                                                         |___/ 

Email: petar@wunki.org
Twitter: @wunki

Tip of the day:
--------------------------------------------------------------------------------
[vagrant@vagrant-freebsd-10 ~]$ 
```

**Comment by FractalizeR** [comment] 2015-02-17 09:02
I've tried everything suggested here and my box still hangs on 

```==> default: Mounting NFS shared folders...```

**Comment by nickdtodd** [comment] 2015-02-17 09:06
@FractalizeR Are you able to start it in gui mode? I can't remember the setting to add to your Vagrant file but it could be that your box is waiting for input. You would be able to see this in gui mode. I'll try and find you a link.

**Comment by nickdtodd** [comment] 2015-02-17 09:09
@FractalizeR maybe something like this: http://stackoverflow.com/questions/19013851/enabling-gui-in-vagrantfile-settings

**Comment by FractalizeR** [comment] 2015-02-17 09:14
The problem was in starting vagrant command from inside PHPStorm. I just started it from pure shell and got password request for modifying /etc/exports on host machine. After that all went fine.

**Comment by gfauredumont** [comment] 2015-02-22 16:54
Hi,

I tumbled upon this thread while looking for a solution (had the same problem on Mint 17.1).

I could fix it by installing the missing package ;)
```sh
sudo apt-get install nfs-kernel-server
```
more on this here:
https://github.com/mitchellh/vagrant/issues/1534

Hope this helps

**Comment by mconigliaro** [comment] 2015-02-26 19:10
I had this problem with Test Kitchen on CentOS 7. I fixed it by giving sudo privileges to the user running Test Kitchen (I have no idea why it just hung rather then giving me some sort of permission denied error).

**Comment by dstosik** [comment] 2015-03-17 06:31
@gfauredumont Thanks, your comment above helped me get it working on Linux Mint 17.1. nfs-kernel-server package was not installed.

**Comment by aftabnaveed** [comment] 2015-03-18 21:10
I am having the same problem, taking out udp from mount_options did not work for me, both my guest and hosts are 14.04 LTS

**Comment by aftabnaveed** [comment] 2015-03-18 21:43
apparently it was my Firewall blocking NFS and rpcbind ports

**Comment by andrewroth** [comment] 2015-04-09 21:08
I'm getting this as well.  Does anyone know a way to manually run the NFS mount?

**Comment by endorama** [comment] 2015-04-13 14:03
Thanks @aftabnaveed! Your [comment](https://github.com/wunki/vagrant-freebsd/issues/4#issuecomment-83194883) made me solve my issue. I had a firewall that was blocking incoming requests and prevented nfs to mount the folder. After disabling the firewall everything was fine.

**Comment by renatomefidf** [comment] 2015-04-19 17:13
In my case it was the firewall, I'm using Fedora 21 and we know that all RH based distros come with a very restrict firewall!

Maybe Vagrant should test with a simple netcat if the door is opened, this would made things easier to deduce!

**Comment by Azulinho** [comment] 2015-05-10 20:13
This config works for me:

\>cat Vagrantfile 
Vagrant.configure("2") do |c|

  c.vm.define :freebsd do |f|
    f.vm.box = "opscode-freebsd-10.1"
    f.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_freebsd-10.1_chef-provisionerless.box"
    f.vm.hostname = "freebsd-10.1"
    f.ssh.shell = '/bin/sh'
    f.vm.network(:private_network, {:ip=>"192.168.33.2"})
    f.vm.synced_folder ".", "/vagrant", disabled: true
    f.vm.synced_folder "/home/azul/gits/azulinho-cuisine", "/vagrant", create: true, type: :nfs, :mount_options => ['nolock,vers=3,tcp,noatime,clientaddr=192.168.33.2']
    f.vm.provider :virtualbox do |p|
      p.gui = false
    end
    f.vm.provision :shell, path: 'tests/freebsd/bootstrap.sh'
  end
end

**Comment by lordgordon** [comment] 2015-06-05 22:06
Hi there,

I have the same problem but I found a simple workaround. In fact,  as soon ```vagrant up``` hangs on the infamous "Mounting NFS" I access the box with ```vagrant ssh```. First, I check it with ps the blocking command:

```
ps -afxu | grep nfs
mount -t nfs -o nfsv3 192.168.1.1:/Users/mypath/myrepo /vagrant
mount_nfs -o nfsv3 192.168.1.1:/Users/mypath/myrepo
```

Then I kill and execute it:
```
sudo killall mount mount_nfs
sudo mount -t nfs -o nfsv3 192.168.1.1:/Users/mypath/myrepo /vagrant
```

And everything works fine. If you have a firewall enable on Guest side make sure to add the proper rules. As example, with Little Snitch for OS X you can temporary disable it to run the mount command and the re-enable it (at least while trying this workaround).

Now, this is really boring and it should work out of the box with Vagrant.

Anyone can figure out why the command executed by Vagrant fails? It's something wrong in FreeBSD or it's really a Vagrant bug?

Thanks for your help!

Regards,

Nicholas

Host: OS X 10.9.5
Guest: FreeBSD 10.1-p10
Vagrantfile:
```
config.vm.network "private_network", ip: "192.168.1.2"
config.vm.synced_folder ".", "/vagrant", create: true, :nfs => true, :mount_options => ['nolock,vers=3,tcp,noatime,clientaddr=192.168.1.2'], id: "vagrant-root"
```

/etc/exports:
```
# VAGRANT-BEGIN: 501 XXX-XXX-XXX
"/Users/mypath/myrepo" 192.168.1.2 -alldirs -mapall=501:20
# VAGRANT-END: 501 XXX-XXX-XXX
```

**Comment by fdemmer** [comment] 2015-07-06 10:18
another hint: i needed to restart the nfs-kernel-server after doing a delete and fresh checkout of a project from git. nfs server was probably looking at the old inode.

**Comment by jakubigla** [comment] 2015-07-09 13:14
I have also had this problem and what what causing this is McAfee. Had to change desktop firewall to adaptive mode. If this is not your case, check your anti-virus settings.

**Comment by psybaron** [comment] 2015-08-22 18:08
For Linux (Ubuntu/Debian) make sure you either stop the firewall or add exception.

    sudo service ufw stop

**Comment by bronger** [comment] 2015-08-27 17:19
@fdemmer, same here; thank you for the hint!  Apparently, this issue can have very many causes.  Better diagnostics would be very helpful.

**Comment by rafaeltuelho** [comment] 2015-09-12 03:06
In my case this issue was solved just installing the `vagrant-nfs_guest` plugin.
After that it simply worked!

**Comment by wunki** [comment] 2015-09-13 12:06
Moving this to documentation soon.

**Closed by wunki** 2015-09-13 12:06 UTC

**Comment by dogawaf** [comment] 2015-10-08 15:51
@rafaeltuelho thx, installing the `vagrant-nfs_guest` plugin solved my issue too. It's weird, because I don't need the features offered by this plugin.

**Comment by stereoplegic** [comment] 2015-10-13 14:13
I'm not using this VM, being an Ubuntu guy (host, guest, and production), but `vagrant-nfs_guest` as suggested by @rafaeltuelho solved my issue with "ubuntu/trusty64". Not sure if `:mount_options => ['nolock,vers=3,udp,noatime']` suggested by @kaamaru played a part, but I've seen it recommended elsewhere for Virtualbox so I'm keeping it. Thanks for the suggestions.

**Comment by bradleyflood** [comment] 2015-10-25 23:45
For anyone on OSX check your Firewall preferences `System Preferences -> Security & Privacy -> Firewall -> Firewall Options`.
Make sure `Automatically allow signed software to receive incoming connections` is checked.

Otherwise just disable the OSX Firewall altogether if you don't need it.

**Comment by lordgordon** [comment] 2015-10-26 07:43
@bradleyflood Actually, I don't have that option enabled and it works fine. In fact I don't think is a good security suggestion.

Please look at your settings, it's not necessary to disable the firewall to make NFS working properly with Vagrant.

**Comment by dadasoz-cuelogic** [comment] 2015-10-27 09:03
Work for me - 

VAGRANT_USE_VBOXFS=true vagrant up

**Comment by bakicdj** [comment] 2015-10-30 18:14
It was a firewall in my case. `sudo ufw disable`  solved it.

**Comment by eduardodx** [comment] 2015-12-07 00:20
Thank you @bradleyflood!

**Comment by netmikey** [comment] 2016-01-08 10:32
Thanks, @bradleyflood!

**Comment by stadnitski** [comment] 2016-06-02 07:16
@bradleyflood THANK YOU!!!

**Comment by mimoralea** [comment] 2016-06-10 21:24
If you are using Fedora, just allow the nfs ports through the firewall, or quickly disable the firewall `sudo systemctl stop firewalld` while you figure it out.

**Comment by tooshay** [comment] 2016-07-28 08:11
We had a similar issue; turns out it was McAfee firewall blocking it all along.

**Comment by rhyw** [comment] 2016-09-05 08:20
My case is that the nfs directory from the host server is not visible on guest.
This http://unix.stackexchange.com/a/243808/188279 resolves it.
PS I'm running on fedora 23, a rhel7.2 box with libvirt.

Hope that helps someone.

**Comment by MeonValleyWeb** [comment] 2016-10-10 09:11
It was McAfee that was blocking the NFS share on Vagrant. Anyone know what rule to put into McAfee to enable this to work as kinda would like the firewall on!

**Comment by chadfurman** [comment] 2017-03-03 01:49
+1 firewall issue.  Had to disable suse's default firewall.  Not ideal, will have to add a rule at somepoint

**Comment by nicklaw5** [comment] 2017-03-03 21:14
For Debian users. If you've configured a private IP for your Vagrant machine, similar to this:
```ruby
config.vm.network "private_network", ip: "192.168.50.50"
```
You just need to add as firewall exception for that specific IP:
```bash
$ sudo ufw allow from 192.168.50.50
$ sudo service ufw restart
```

**Comment by chadfurman** [comment] 2017-03-06 15:25
for SuSE users: edit `/etc/sysconfig/SuSEfirewall2`

find `FW_TRUSTED_NETS` and add the VBox net.

i.e. `FW_TRUSTED_NETS="192.168.33.0/24"`

then re-issue the firewall command to reload rules:

`# SuSEfirewall2`

**Comment by chadfurman** [comment] 2017-05-27 16:04
I had a similar problem in Ubuntu, Vagrant version 1.9.3, VB version 5.1.22

The problem was that my host's OS has changed the `ifconfig` to the `ip` command, and `vboxnet0` did not have an ip address. 

I had to run:

`ip a add 192.168.33.1/255.255.255.0 dev vboxnet0` before Vagrant could start the NFS share

There were many other things I tried: starting/stopping the firewall (ufw, iptables, both, neither); adding specific rules to the firewall to allow all traffic to this IP; `service start` for each of nfs-common, nfs-kernel-server, nfs-server, nfs-client; and clearing out my /etc/exports

It wasn't until I made sure my vboxnet0 had an IP on the host machine that everything worked.

*EDIT: DON'T FORGET TO LINK YOUR INTERFACE!*
`$ sudo ip link set vboxnet0 up`

**Comment by cfebs** [comment] 2017-07-20 16:54
Ubuntu 16.04.2
Virtualbox Version 5.1.24 r117012 (Qt5.5.1)
Vagrant 1.9.7

Similar to @chadfurman , `ifconfig -a` showed my vboxnet0 host only interface down but it had an ip, so `sudo ifconfig vboxnet0 up` was the fix.

Not exactly sure why but i'll be keeping an eye out on reboot, I believe i just updated virtualbox versions.

UPDATE

So yes my host only network will not come up when vagrant starts anymore, very interesting. My vagrant file line for the private network is: `config.vm.network "private_network", ip: IP_ADDR, nictype: "virtio"`

Also it looks like the real source of the issue is being discussed here: https://github.com/mitchellh/vagrant/issues/8166

**Comment by midia-developer** [comment] 2018-03-22 17:56
Docker had added a similar entity for me at 
/Users

So Vagrant was unable to share the NFS
/Users/jonw/Sites 

Fixed by commentating out the docker line
